.TH "/home/robin/NetbeansProjects/sincontrol/app/lang/nl Directory Reference" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/robin/NetbeansProjects/sincontrol/app/lang/nl Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBpagination\&.php\fP"
.br
.ti -1c
.RI "file \fBreminders\&.php\fP"
.br
.ti -1c
.RI "file \fBvalidation\&.php\fP"
.br
.in -1c
