.TH "/home/robin/NetbeansProjects/sincontrol/app/views/website Directory Reference" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/robin/NetbeansProjects/sincontrol/app/views/website Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBvhost\fP"
.br
.in -1c
