.TH "/home/robin/NetbeansProjects/sincontrol/scripts Directory Reference" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/robin/NetbeansProjects/sincontrol/scripts Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBApacheVhostVirtual\&.php\fP"
.br
.ti -1c
.RI "file \fBcron\&.php\fP"
.br
.ti -1c
.RI "file \fBServiceApache\&.php\fP"
.br
.ti -1c
.RI "file \fBSystemTask\&.php\fP"
.br
.in -1c
