.TH "/home/robin/NetbeansProjects/sincontrol/app/views/user Directory Reference" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/robin/NetbeansProjects/sincontrol/app/views/user Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBamnesia\&.blade\&.php\fP"
.br
.ti -1c
.RI "file \fBedit\&.blade\&.php\fP"
.br
.ti -1c
.RI "file \fBexpired\&.blade\&.php\fP"
.br
.ti -1c
.RI "file \fBlogin\&.blade\&.php\fP"
.br
.ti -1c
.RI "file \fBregister\&.blade\&.php\fP"
.br
.ti -1c
.RI "file \fBstart\&.blade\&.php\fP"
.br
.in -1c
