.TH "/home/robin/NetbeansProjects/sincontrol/app Directory Reference" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/robin/NetbeansProjects/sincontrol/app Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBcontrollers\fP"
.br
.ti -1c
.RI "directory \fBlang\fP"
.br
.ti -1c
.RI "directory \fBlibraries\fP"
.br
.ti -1c
.RI "directory \fBmodels\fP"
.br
.ti -1c
.RI "directory \fBviews\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBerrors\&.php\fP"
.br
.ti -1c
.RI "file \fBfilters\&.php\fP"
.br
.ti -1c
.RI "file \fBmenu\&.php\fP"
.br
.ti -1c
.RI "file \fBroutes\&.php\fP"
.br
.ti -1c
.RI "file \fBvalidators\&.php\fP"
.br
.in -1c
