.TH "Alert" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Alert \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($message, $type= '', $close=false)"
.br
.ti -1c
.RI "\fBgetMessage\fP ()"
.br
.ti -1c
.RI "\fBgetType\fP ()"
.br
.ti -1c
.RI "\fBsetMessage\fP ($message)"
.br
.ti -1c
.RI "\fBsetType\fP ($type)"
.br
.ti -1c
.RI "\fBgetClose\fP ()"
.br
.ti -1c
.RI "\fBsetClose\fP ($close)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fB$message\fP"
.br
.ti -1c
.RI "\fB$type\fP"
.br
.ti -1c
.RI "\fB$close\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $message,  $type = \fC''\fP,  $close = \fCfalse\fP)"

.SH "Member Function Documentation"
.PP 
.SS "getClose ()"

.SS "getMessage ()"

.SS "getType ()"

.SS "setClose ( $close)"

.SS "setMessage ( $message)"

.SS "setType ( $type)"

.SH "Field Documentation"
.PP 
.SS "$close\fC [private]\fP"

.SS "$message\fC [private]\fP"

.SS "$type\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for SINControl from the source code\&.
