.TH "ApacheVhostVirtual" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ApacheVhostVirtual \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLimitedUserOwnedModel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($servername, $serveralias, $serveradmin, $ssl, $username, $group)"
.br
.ti -1c
.RI "\fB__get\fP ($property)"
.br
.ti -1c
.RI "\fBnuke\fP ()"
.br
.ti -1c
.RI "\fBsave\fP (array $options=array())"
.br
.ti -1c
.RI "\fBdelete\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBget\fP ($db)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBVHOSTDIRAVAILABLE\fP = '/etc/apache2/sites-available/'"
.br
.ti -1c
.RI "const \fBVHOSTDIRENABLED\fP = '/etc/apache2/sites-enabled/'"
.br
.ti -1c
.RI "const \fBSSLCERT\fP = '/etc/apache2/ssl/wildcard\&.sinners\&.be\&.cert'"
.br
.ti -1c
.RI "const \fBSSLKEY\fP = '/etc/apache2/ssl/wildcard\&.sinners\&.be\&.key'"
.br
.ti -1c
.RI "const \fBEXPIRED_DOCROOT\fP = '/var/www/expired/'"
.br
.ti -1c
.RI "\fB$timestamps\fP = false"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$table\fP = 'apache_vhost_virtual'"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fB$properties\fP = array ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $servername,  $serveralias,  $serveradmin,  $ssl,  $username,  $group)"

.SH "Member Function Documentation"
.PP 
.SS "__get ( $property)"

.SS "delete ()"

.SS "static get ( $db)\fC [static]\fP"

.SS "nuke ()"

.SS "save (array $options = \fCarray ()\fP)"

.SH "Field Documentation"
.PP 
.SS "$properties = array ()\fC [private]\fP"

.SS "$table = 'apache_vhost_virtual'\fC [protected]\fP"

.SS "$timestamps = false"

.SS "const EXPIRED_DOCROOT = '/var/www/expired/'"

.SS "const SSLCERT = '/etc/apache2/ssl/wildcard\&.sinners\&.be\&.cert'"

.SS "const SSLKEY = '/etc/apache2/ssl/wildcard\&.sinners\&.be\&.key'"

.SS "const VHOSTDIRAVAILABLE = '/etc/apache2/sites-available/'"

.SS "const VHOSTDIRENABLED = '/etc/apache2/sites-enabled/'"


.SH "Author"
.PP 
Generated automatically by Doxygen for SINControl from the source code\&.
