.TH "BaseController" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BaseController \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Controller\&.
.PP
Inherited by \fBDatabaseController\fP, \fBErrorController\fP, \fBFtpController\fP, \fBHomeController\fP, \fBMailController\fP, \fBMailDomainController\fP, \fBMailForwardingController\fP, \fBMailUserController\fP, \fBPageController\fP, \fBStaffAbuseController\fP, \fBStaffFtpController\fP, \fBStaffGroupController\fP, \fBStaffMailController\fP, \fBStaffMailDomainController\fP, \fBStaffMailForwardingController\fP, \fBStaffMailUserController\fP, \fBStaffMaintenanceController\fP, \fBStaffPageController\fP, \fBStaffSystemTaskController\fP, \fBStaffUserController\fP, \fBStaffUserLimitController\fP, \fBStaffUserLogController\fP, \fBStaffVHostController\fP, \fBStaffVirtualisationController\fP, \fBUserController\fP, and \fBVHostController\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBsetupLayout\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "setupLayout ()\fC [protected]\fP"
Setup the layout used by the controller\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SINControl from the source code\&.
