.TH "CryptHash" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CryptHash \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits HasherInterface\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmake\fP ($value, array $options=array())"
.br
.ti -1c
.RI "\fBcheck\fP ($value, $hashedValue, array $options=array())"
.br
.ti -1c
.RI "\fBneedsRehash\fP ($hashedValue, array $options=array())"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "check ( $value,  $hashedValue, array $options = \fCarray ()\fP)"
Check the given plain value against a hash\&.
.PP
\fBParameters:\fP
.RS 4
\fI$value\fP 
.br
\fI$hashedValue\fP 
.br
\fI$options\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.SS "make ( $value, array $options = \fCarray ()\fP)"
Hash the given value\&.
.PP
\fBParameters:\fP
.RS 4
\fI$value\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
array $options 
.PP
string 
.RE
.PP

.SS "needsRehash ( $hashedValue, array $options = \fCarray ()\fP)"
Check if the given hash has been hashed using the given options\&.
.PP
\fBParameters:\fP
.RS 4
\fI$hashedValue\fP 
.br
\fI$options\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SINControl from the source code\&.
