.TH "CryptHashServiceProvider" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CryptHashServiceProvider \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits ServiceProvider\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBregister\fP ()"
.br
.ti -1c
.RI "\fBprovides\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "provides ()"
Get the services provided by the provider\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.SS "register ()"
Register the service provider\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SINControl from the source code\&.
