.TH "DatabaseCredentials" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DatabaseCredentials \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBforUserPrimary\fP ($username, $password)"
.br
.ti -1c
.RI "static \fBforUserPrimary_hash\fP ($username, $hash)"
.br
.ti -1c
.RI "static \fBgetHash\fP ($password)"
.br
.ti -1c
.RI "static \fBforUser\fP (\fBUser\fP $user)"
.br
.in -1c
.SS "Static Private Member Functions"

.in +1c
.ti -1c
.RI "static \fBgeneratePassword\fP ()"
.br
.ti -1c
.RI "static \fBgenerateRandom\fP ($length)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static forUser (\fBUser\fP $user)\fC [static]\fP"

.SS "static forUserPrimary ( $username,  $password)\fC [static]\fP"

.SS "static forUserPrimary_hash ( $username,  $hash)\fC [static]\fP"

.SS "static generatePassword ()\fC [static]\fP, \fC [private]\fP"

.SS "static generateRandom ( $length)\fC [static]\fP, \fC [private]\fP"

.SS "static getHash ( $password)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for SINControl from the source code\&.
