.TH "FtpController" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FtpController \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBaseController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBindex\fP ()"
.br
.ti -1c
.RI "\fBcreate\fP ()"
.br
.ti -1c
.RI "\fBstore\fP ()"
.br
.ti -1c
.RI "\fBedit\fP ($ftp)"
.br
.ti -1c
.RI "\fBupdate\fP ($ftp)"
.br
.ti -1c
.RI "\fBremove\fP ($ftp)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "create ()"

.SS "edit ( $ftp)"

.SS "index ()"

.SS "remove ( $ftp)"

.SS "store ()"

.SS "update ( $ftp)"


.SH "Author"
.PP 
Generated automatically by Doxygen for SINControl from the source code\&.
