.TH "LimitedUserOwnedModel" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LimitedUserOwnedModel \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUserOwnedModel\fP\&.
.PP
Inherited by \fBApacheVhostVirtual\fP, \fBFtpUserVirtual\fP, \fBMailDomainVirtual\fP, \fBMailForwardingVirtual\fP, and \fBMailUserVirtual\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBgetTableName\fP ()"
.br
.ti -1c
.RI "static \fBallowNew\fP (\fBUser\fP $user)"
.br
.ti -1c
.RI "static \fBgetCount\fP (\fBUser\fP $user)"
.br
.ti -1c
.RI "static \fBgetLimit\fP (\fBUser\fP $user)"
.br
.ti -1c
.RI "static \fBgetGlobalLimit\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "static allowNew (\fBUser\fP $user)\fC [static]\fP"

.SS "static getCount (\fBUser\fP $user)\fC [static]\fP"

.SS "static getGlobalLimit ()\fC [static]\fP"

.SS "static getLimit (\fBUser\fP $user)\fC [static]\fP"

.SS "static getTableName ()\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for SINControl from the source code\&.
