.TH "MenuItem" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MenuItem \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Eloquent\&.
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$timestamps\fP = false"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$table\fP = 'menuitem'"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "$table = 'menuitem'\fC [protected]\fP"

.SS "$timestamps = false"


.SH "Author"
.PP 
Generated automatically by Doxygen for SINControl from the source code\&.
