.TH "Page" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Page \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Eloquent\&.
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$timestamps\fP = true"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$table\fP = 'page'"
.br
.ti -1c
.RI "\fB$softDelete\fP = true"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "$softDelete = true\fC [protected]\fP"

.SS "$table = 'page'\fC [protected]\fP"

.SS "$timestamps = true"


.SH "Author"
.PP 
Generated automatically by Doxygen for SINControl from the source code\&.
