.TH "Proxmox" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Proxmox \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBProxmoxClass\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($username, $password)"
.br
.ti -1c
.RI "\fBgetNodes\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $username,  $password)"

.SH "Member Function Documentation"
.PP 
.SS "getNodes ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for SINControl from the source code\&.
