.TH "ProxmoxNodeService" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProxmoxNodeService \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBProxmoxClass\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($api, $node, $data)"
.br
.ti -1c
.RI "\fBgetNode\fP ()"
.br
.ti -1c
.RI "\fBgetName\fP ()"
.br
.ti -1c
.RI "\fBgetFriendlyName\fP ()"
.br
.ti -1c
.RI "\fBgetDescription\fP ()"
.br
.ti -1c
.RI "\fBgetState\fP ()"
.br
.ti -1c
.RI "\fBreload\fP ()"
.br
.ti -1c
.RI "\fBrestart\fP ()"
.br
.ti -1c
.RI "\fBstart\fP ()"
.br
.ti -1c
.RI "\fBstop\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBget\fP ($url, $postFields=null)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fB$node\fP"
.br
.ti -1c
.RI "\fB$serviceName\fP"
.br
.ti -1c
.RI "\fB$friendlyName\fP"
.br
.ti -1c
.RI "\fB$description\fP"
.br
.ti -1c
.RI "\fB$state\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $api,  $node,  $data)"

.SH "Member Function Documentation"
.PP 
.SS "get ( $url,  $postFields = \fCnull\fP)\fC [protected]\fP"

.SS "getDescription ()"

.SS "getFriendlyName ()"

.SS "getName ()"

.SS "getNode ()"

.SS "getState ()"

.SS "reload ()"

.SS "restart ()"

.SS "start ()"

.SS "stop ()"

.SH "Field Documentation"
.PP 
.SS "$description\fC [private]\fP"

.SS "$friendlyName\fC [private]\fP"

.SS "$node\fC [private]\fP"

.SS "$serviceName\fC [private]\fP"

.SS "$state\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for SINControl from the source code\&.
