.TH "ProxmoxNodeVM" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProxmoxNodeVM \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBProxmoxClass\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($node, $data)"
.br
.ti -1c
.RI "\fBgetNode\fP ()"
.br
.ti -1c
.RI "\fBgetId\fP ()"
.br
.ti -1c
.RI "\fBgetName\fP ()"
.br
.ti -1c
.RI "\fBgetState\fP ()"
.br
.ti -1c
.RI "\fBisTemplate\fP ()"
.br
.ti -1c
.RI "\fBgetDisk\fP ()"
.br
.ti -1c
.RI "\fBgetMaxDisk\fP ()"
.br
.ti -1c
.RI "\fBgetMaxMem\fP ()"
.br
.ti -1c
.RI "\fBgetCPU\fP ()"
.br
.ti -1c
.RI "\fBgetMem\fP ()"
.br
.ti -1c
.RI "\fBgetCPUs\fP ()"
.br
.ti -1c
.RI "\fBgetDiskRead\fP ()"
.br
.ti -1c
.RI "\fBgetDiskWrite\fP ()"
.br
.ti -1c
.RI "\fBgetNetIn\fP ()"
.br
.ti -1c
.RI "\fBgetNetOut\fP ()"
.br
.ti -1c
.RI "\fBgetMemoryUsage\fP ()"
.br
.ti -1c
.RI "\fBgetDiskUsage\fP ()"
.br
.ti -1c
.RI "\fBgetCPUUsage\fP ()"
.br
.ti -1c
.RI "\fBreset\fP ()"
.br
.ti -1c
.RI "\fBresume\fP ()"
.br
.ti -1c
.RI "\fBshutdown\fP ()"
.br
.ti -1c
.RI "\fBstart\fP ()"
.br
.ti -1c
.RI "\fBstop\fP ()"
.br
.ti -1c
.RI "\fBsuspend\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBget\fP ($url, $postFields=null)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fB$node\fP"
.br
.ti -1c
.RI "\fB$id\fP"
.br
.ti -1c
.RI "\fB$name\fP"
.br
.ti -1c
.RI "\fB$state\fP"
.br
.ti -1c
.RI "\fB$template\fP"
.br
.ti -1c
.RI "\fB$disk\fP"
.br
.ti -1c
.RI "\fB$maxDisk\fP"
.br
.ti -1c
.RI "\fB$maxMem\fP"
.br
.ti -1c
.RI "\fB$cpu\fP"
.br
.ti -1c
.RI "\fB$mem\fP"
.br
.ti -1c
.RI "\fB$cpus\fP"
.br
.ti -1c
.RI "\fB$diskRead\fP"
.br
.ti -1c
.RI "\fB$diskWrite\fP"
.br
.ti -1c
.RI "\fB$netIn\fP"
.br
.ti -1c
.RI "\fB$netOut\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $node,  $data)"

.SH "Member Function Documentation"
.PP 
.SS "get ( $url,  $postFields = \fCnull\fP)\fC [protected]\fP"

.SS "getCPU ()"

.SS "getCPUs ()"

.SS "getCPUUsage ()"

.SS "getDisk ()"

.SS "getDiskRead ()"

.SS "getDiskUsage ()"

.SS "getDiskWrite ()"

.SS "getId ()"

.SS "getMaxDisk ()"

.SS "getMaxMem ()"

.SS "getMem ()"

.SS "getMemoryUsage ()"

.SS "getName ()"

.SS "getNetIn ()"

.SS "getNetOut ()"

.SS "getNode ()"

.SS "getState ()"

.SS "isTemplate ()"

.SS "reset ()"

.SS "resume ()"

.SS "shutdown ()"

.SS "start ()"

.SS "stop ()"

.SS "suspend ()"

.SH "Field Documentation"
.PP 
.SS "$cpu\fC [private]\fP"

.SS "$cpus\fC [private]\fP"

.SS "$disk\fC [private]\fP"

.SS "$diskRead\fC [private]\fP"

.SS "$diskWrite\fC [private]\fP"

.SS "$id\fC [private]\fP"

.SS "$maxDisk\fC [private]\fP"

.SS "$maxMem\fC [private]\fP"

.SS "$mem\fC [private]\fP"

.SS "$name\fC [private]\fP"

.SS "$netIn\fC [private]\fP"

.SS "$netOut\fC [private]\fP"

.SS "$node\fC [private]\fP"

.SS "$state\fC [private]\fP"

.SS "$template\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for SINControl from the source code\&.
