.TH "ServiceApache" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ServiceApache \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSystemService\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBreload\fP ()"
.br
.ti -1c
.RI "\fBreload\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBINIT\fP = 'sysvinit'"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$name\fP = 'Web server'"
.br
.ti -1c
.RI "\fB$serverName\fP = 'Web'"
.br
.ti -1c
.RI "\fB$software\fP = 'apache2'"
.br
.ti -1c
.RI "\fB$ssh\fP = null"
.br
.ti -1c
.RI "\fB$needsSudo\fP = false"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "reload ()"

.SS "reload ()"

.SH "Field Documentation"
.PP 
.SS "$name = 'Web server'\fC [protected]\fP"

.SS "$needsSudo = false\fC [protected]\fP"

.SS "$serverName = 'Web'\fC [protected]\fP"

.SS "$software = 'apache2'\fC [protected]\fP"

.SS "$ssh = null\fC [protected]\fP"

.SS "const INIT = 'sysvinit'"


.SH "Author"
.PP 
Generated automatically by Doxygen for SINControl from the source code\&.
