.TH "/home/robin/NetbeansProjects/sincontrol/app/controllers/StaffUserLogController.php" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/robin/NetbeansProjects/sincontrol/app/controllers/StaffUserLogController.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBStaffUserLogController\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SINControl from the source code\&.
