.TH "StaffUserLogController" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StaffUserLogController \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBaseController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBindex\fP ()"
.br
.ti -1c
.RI "\fBsearch\fP ()"
.br
.ti -1c
.RI "\fBeditChecked\fP ()"
.br
.ti -1c
.RI "\fBexport\fP ()"
.br
.ti -1c
.RI "\fBcreate\fP ()"
.br
.ti -1c
.RI "\fBstore\fP ()"
.br
.ti -1c
.RI "\fBedit\fP ($userlog)"
.br
.ti -1c
.RI "\fBupdate\fP ($userlog)"
.br
.ti -1c
.RI "\fBremove\fP ($userlog)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fB$boekhoudingBetekenis\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "create ()"

.SS "edit ( $userlog)"

.SS "editChecked ()"

.SS "export ()"

.SS "index ()"

.SS "remove ( $userlog)"

.SS "search ()"

.SS "store ()"

.SS "update ( $userlog)"

.SH "Field Documentation"
.PP 
.SS "$boekhoudingBetekenis\fC [private]\fP"
\fBInitial value:\fP
.PP
.nf
= array
    (
        -1 => 'Niet te factureren',
        0 => 'Nog te factureren',
        1 => 'Gefactureerd'
    )
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for SINControl from the source code\&.
