.TH "StaffMaintenanceController" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StaffMaintenanceController \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBaseController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgenerateVHosts\fP ()"
.br
.ti -1c
.RI "\fBsaveAllVHosts\fP ()"
.br
.ti -1c
.RI "\fBgenerateServiceData\fP ()"
.br
.ti -1c
.RI "\fBsystemCheck\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "generateServiceData ()"

.SS "generateVHosts ()"

.SS "saveAllVHosts ()"

.SS "systemCheck ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for SINControl from the source code\&.
