.TH "StaffUserController" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StaffUserController \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBaseController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBindex\fP ($order= 'uid')"
.br
.ti -1c
.RI "\fBsearch\fP ()"
.br
.ti -1c
.RI "\fBcreate\fP ()"
.br
.ti -1c
.RI "\fBstore\fP ()"
.br
.ti -1c
.RI "\fBedit\fP ($user)"
.br
.ti -1c
.RI "\fBupdate\fP ($user)"
.br
.ti -1c
.RI "\fBremove\fP ($user)"
.br
.ti -1c
.RI "\fBlogin\fP ($user)"
.br
.ti -1c
.RI "\fBgetExpire\fP ($user)"
.br
.ti -1c
.RI "\fBexpire\fP ($user)"
.br
.ti -1c
.RI "\fBgetValidate\fP ($userInfo)"
.br
.ti -1c
.RI "\fBvalidate\fP ($userInfo)"
.br
.ti -1c
.RI "\fBreject\fP ($userInfo)"
.br
.ti -1c
.RI "\fBmore\fP ($user)"
.br
.ti -1c
.RI "\fBgenerateLoginToken\fP ($user)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "create ()"

.SS "edit ( $user)"

.SS "expire ( $user)"

.SS "generateLoginToken ( $user)"

.SS "getExpire ( $user)"

.SS "getValidate ( $userInfo)"

.SS "index ( $order = \fC'uid'\fP)"

.SS "login ( $user)"

.SS "more ( $user)"

.SS "reject ( $userInfo)"

.SS "remove ( $user)"

.SS "search ()"

.SS "store ()"

.SS "update ( $user)"

.SS "validate ( $userInfo)"


.SH "Author"
.PP 
Generated automatically by Doxygen for SINControl from the source code\&.
