.TH "UserController" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UserController \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBaseController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstart\fP ()"
.br
.ti -1c
.RI "\fBgetLogin\fP ()"
.br
.ti -1c
.RI "\fBlogin\fP ()"
.br
.ti -1c
.RI "\fBedit\fP ()"
.br
.ti -1c
.RI "\fBupdate\fP ()"
.br
.ti -1c
.RI "\fBlogout\fP ()"
.br
.ti -1c
.RI "\fBgetRegister\fP ()"
.br
.ti -1c
.RI "\fBregister\fP ()"
.br
.ti -1c
.RI "\fBgetExpired\fP ($user)"
.br
.ti -1c
.RI "\fBexpired\fP ($user)"
.br
.ti -1c
.RI "\fBrenew\fP ($user, $validationcode)"
.br
.ti -1c
.RI "\fBgetAmnesia\fP ()"
.br
.ti -1c
.RI "\fBamnesia\fP ()"
.br
.ti -1c
.RI "\fBloginWithToken\fP ($user, $logintoken)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "amnesia ()"

.SS "edit ()"

.SS "expired ( $user)"

.SS "getAmnesia ()"

.SS "getExpired ( $user)"

.SS "getLogin ()"

.SS "getRegister ()"

.SS "login ()"

.SS "loginWithToken ( $user,  $logintoken)"

.SS "logout ()"

.SS "register ()"

.SS "renew ( $user,  $validationcode)"

.SS "start ()"

.SS "update ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for SINControl from the source code\&.
