.TH "UserInfo" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UserInfo \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Eloquent\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetUser\fP ()"
.br
.ti -1c
.RI "\fBuserExists\fP ()"
.br
.ti -1c
.RI "\fBuser_log\fP ()"
.br
.ti -1c
.RI "\fBuser\fP ()"
.br
.ti -1c
.RI "\fBgetFullName\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$timestamps\fP = false"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$table\fP = 'user_info'"
.br
.ti -1c
.RI "\fB$hidden\fP = array ('etc')"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "getFullName ()"

.SS "getUser ()"

.SS "user ()"

.SS "user_log ()"

.SS "userExists ()"

.SH "Field Documentation"
.PP 
.SS "$hidden = array ('etc')\fC [protected]\fP"

.SS "$table = 'user_info'\fC [protected]\fP"

.SS "$timestamps = false"


.SH "Author"
.PP 
Generated automatically by Doxygen for SINControl from the source code\&.
