.TH "User" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
User \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Eloquent, UserInterface, and RemindableInterface\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetPassword\fP ($password)"
.br
.ti -1c
.RI "\fBgetUserInfo\fP ()"
.br
.ti -1c
.RI "\fBuser_info\fP ()"
.br
.ti -1c
.RI "\fBgetGroup\fP ()"
.br
.ti -1c
.RI "\fBgetGroups\fP ()"
.br
.ti -1c
.RI "\fBisGroupMember\fP ($group)"
.br
.ti -1c
.RI "\fBgetLowestGid\fP ()"
.br
.ti -1c
.RI "\fBhasExpired\fP ()"
.br
.ti -1c
.RI "\fBgetAuthIdentifier\fP ()"
.br
.ti -1c
.RI "\fBgetAuthPassword\fP ()"
.br
.ti -1c
.RI "\fBgetRememberToken\fP ()"
.br
.ti -1c
.RI "\fBsetRememberToken\fP ($value)"
.br
.ti -1c
.RI "\fBgetRememberTokenName\fP ()"
.br
.ti -1c
.RI "\fBgetReminderEmail\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$timestamps\fP = false"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$table\fP = 'user'"
.br
.ti -1c
.RI "\fB$hidden\fP = array ('crypt')"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "getAuthIdentifier ()"
Get the unique identifier for the user\&.
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.SS "getAuthPassword ()"
Get the password for the user\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.SS "getGroup ()"

.SS "getGroups ()"

.SS "getLowestGid ()"

.SS "getRememberToken ()"
Get the token value for the 'remember me' session\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.SS "getRememberTokenName ()"
Get the column name for the 'remember me' token\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.SS "getReminderEmail ()"
Get the e-mail address where password reminders are sent\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.SS "getUserInfo ()"

.SS "hasExpired ()"

.SS "isGroupMember ( $group)"

.SS "setPassword ( $password)"

.SS "setRememberToken ( $value)"
Set the token value for the 'remember me' session\&.
.PP
\fBParameters:\fP
.RS 4
\fI$value\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "user_info ()"

.SH "Field Documentation"
.PP 
.SS "$hidden = array ('crypt')\fC [protected]\fP"

.SS "$table = 'user'\fC [protected]\fP"

.SS "$timestamps = false"


.SH "Author"
.PP 
Generated automatically by Doxygen for SINControl from the source code\&.
