.TH "UserLog" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UserLog \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Eloquent\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBuser_info\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$timestamps\fP = false"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$table\fP = 'user_log'"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "user_info ()"

.SH "Field Documentation"
.PP 
.SS "$table = 'user_log'\fC [protected]\fP"

.SS "$timestamps = false"


.SH "Author"
.PP 
Generated automatically by Doxygen for SINControl from the source code\&.
