.TH "/home/robin/NetbeansProjects/sincontrol/app/views Directory Reference" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/robin/NetbeansProjects/sincontrol/app/views Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBdatabase\fP"
.br
.ti -1c
.RI "directory \fBemails\fP"
.br
.ti -1c
.RI "directory \fBftp\fP"
.br
.ti -1c
.RI "directory \fBlayout\fP"
.br
.ti -1c
.RI "directory \fBmail\fP"
.br
.ti -1c
.RI "directory \fBstaff\fP"
.br
.ti -1c
.RI "directory \fBuser\fP"
.br
.ti -1c
.RI "directory \fBwebsite\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcontrolMenu\&.blade\&.php\fP"
.br
.ti -1c
.RI "file \fBhome\&.blade\&.php\fP"
.br
.ti -1c
.RI "file \fBpage\&.blade\&.php\fP"
.br
.ti -1c
.RI "file \fBpagination\&.blade\&.php\fP"
.br
.ti -1c
.RI "file \fBsiteMenu\&.blade\&.php\fP"
.br
.ti -1c
.RI "file \fBstaffMenu\&.blade\&.php\fP"
.br
.ti -1c
.RI "file \fBstatus\&.blade\&.php\fP"
.br
.in -1c
