.TH "/home/robin/NetbeansProjects/sincontrol/app/views/staff/mail/forwarding Directory Reference" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/robin/NetbeansProjects/sincontrol/app/views/staff/mail/forwarding Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcreate\&.blade\&.php\fP"
.br
.ti -1c
.RI "file \fBedit\&.blade\&.php\fP"
.br
.ti -1c
.RI "file \fBindex\&.blade\&.php\fP"
.br
.in -1c
