.TH "/home/robin/NetbeansProjects/sincontrol/app/views/staff/user Directory Reference" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/robin/NetbeansProjects/sincontrol/app/views/staff/user Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBabuse\fP"
.br
.ti -1c
.RI "directory \fBgroup\fP"
.br
.ti -1c
.RI "directory \fBlimit\fP"
.br
.ti -1c
.RI "directory \fBlog\fP"
.br
.ti -1c
.RI "directory \fBuser\fP"
.br
.in -1c
