.TH "/home/robin/NetbeansProjects/sincontrol/app/views/emails/auth Directory Reference" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/robin/NetbeansProjects/sincontrol/app/views/emails/auth Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBreminder\&.blade\&.php\fP"
.br
.in -1c
