.TH "MailDomainController" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MailDomainController \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBaseController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBindex\fP ()"
.br
.ti -1c
.RI "\fBcreate\fP ()"
.br
.ti -1c
.RI "\fBstore\fP ()"
.br
.ti -1c
.RI "\fBedit\fP ($domain)"
.br
.ti -1c
.RI "\fBupdate\fP ($domain)"
.br
.ti -1c
.RI "\fBremove\fP ($domain)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "create ()"

.SS "edit ( $domain)"

.SS "index ()"

.SS "remove ( $domain)"

.SS "store ()"

.SS "update ( $domain)"


.SH "Author"
.PP 
Generated automatically by Doxygen for SINControl from the source code\&.
