.TH "MailUserVirtual" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MailUserVirtual \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLimitedUserOwnedModel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetPassword\fP ($password)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$timestamps\fP = false"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$table\fP = 'mail_user_virtual'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "setPassword ( $password)"

.SH "Field Documentation"
.PP 
.SS "$table = 'mail_user_virtual'\fC [protected]\fP"

.SS "$timestamps = false"


.SH "Author"
.PP 
Generated automatically by Doxygen for SINControl from the source code\&.
