.TH "Menu" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Menu \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBgetControl\fP ()"
.br
.ti -1c
.RI "static \fBgetSite\fP ()"
.br
.ti -1c
.RI "static \fBgetStaff\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static getControl ()\fC [static]\fP"

.SS "static getSite ()\fC [static]\fP"

.SS "static getStaff ()\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for SINControl from the source code\&.
