.TH "PaginationPresenter" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PaginationPresenter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Presenter\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetActivePageWrapper\fP ($text)"
.br
.ti -1c
.RI "\fBgetDisabledTextWrapper\fP ($text)"
.br
.ti -1c
.RI "\fBgetPageLinkWrapper\fP ($url, $page, $rel=null)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "getActivePageWrapper ( $text)"

.SS "getDisabledTextWrapper ( $text)"

.SS "getPageLinkWrapper ( $url,  $page,  $rel = \fCnull\fP)"


.SH "Author"
.PP 
Generated automatically by Doxygen for SINControl from the source code\&.
