.TH "ProxmoxNode" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProxmoxNode \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBProxmoxClass\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($api, $data)"
.br
.ti -1c
.RI "\fBgetSysLog\fP ()"
.br
.ti -1c
.RI "\fBgetVersion\fP ()"
.br
.ti -1c
.RI "\fBgetStatus\fP ()"
.br
.ti -1c
.RI "\fBgetBootLog\fP ()"
.br
.ti -1c
.RI "\fBgetName\fP ()"
.br
.ti -1c
.RI "\fBgetDisk\fP ()"
.br
.ti -1c
.RI "\fBgetCPU\fP ()"
.br
.ti -1c
.RI "\fBgetMaxDisk\fP ()"
.br
.ti -1c
.RI "\fBgetMaxMem\fP ()"
.br
.ti -1c
.RI "\fBgetMaxCPU\fP ()"
.br
.ti -1c
.RI "\fBgetUptime\fP ()"
.br
.ti -1c
.RI "\fBgetUptimeDays\fP ()"
.br
.ti -1c
.RI "\fBgetMem\fP ()"
.br
.ti -1c
.RI "\fBgetCPUUsage\fP ()"
.br
.ti -1c
.RI "\fBgetMemoryUsage\fP ()"
.br
.ti -1c
.RI "\fBgetDiskUsage\fP ()"
.br
.ti -1c
.RI "\fBgetServices\fP ()"
.br
.ti -1c
.RI "\fBgetNetworkInterfaces\fP ()"
.br
.ti -1c
.RI "\fBgetVMs\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBget\fP ($url, $postFields=null)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fB$nodeName\fP"
.br
.ti -1c
.RI "\fB$disk\fP"
.br
.ti -1c
.RI "\fB$cpu\fP"
.br
.ti -1c
.RI "\fB$maxDisk\fP"
.br
.ti -1c
.RI "\fB$maxMem\fP"
.br
.ti -1c
.RI "\fB$maxCPU\fP"
.br
.ti -1c
.RI "\fB$uptime\fP"
.br
.ti -1c
.RI "\fB$mem\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $api,  $data)"

.SH "Member Function Documentation"
.PP 
.SS "get ( $url,  $postFields = \fCnull\fP)\fC [protected]\fP"

.SS "getBootLog ()"

.SS "getCPU ()"

.SS "getCPUUsage ()"

.SS "getDisk ()"

.SS "getDiskUsage ()"

.SS "getMaxCPU ()"

.SS "getMaxDisk ()"

.SS "getMaxMem ()"

.SS "getMem ()"

.SS "getMemoryUsage ()"

.SS "getName ()"

.SS "getNetworkInterfaces ()"

.SS "getServices ()"

.SS "getStatus ()"

.SS "getSysLog ()"

.SS "getUptime ()"

.SS "getUptimeDays ()"

.SS "getVersion ()"

.SS "getVMs ()"

.SH "Field Documentation"
.PP 
.SS "$cpu\fC [private]\fP"

.SS "$disk\fC [private]\fP"

.SS "$maxCPU\fC [private]\fP"

.SS "$maxDisk\fC [private]\fP"

.SS "$maxMem\fC [private]\fP"

.SS "$mem\fC [private]\fP"

.SS "$nodeName\fC [private]\fP"

.SS "$uptime\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for SINControl from the source code\&.
