.TH "ProxmoxClass" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProxmoxClass \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBProxmox\fP, \fBProxmoxNode\fP, \fBProxmoxNodeService\fP, and \fBProxmoxNodeVM\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpassAuthentication\fP (\fBProxmoxClass\fP $api)"
.br
.ti -1c
.RI "\fBreceiveAuthentication\fP ($token, $ticket)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBAPI\fP = 'https://192\&.168\&.80\&.21:8006/api2/json/'"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBauthenticate\fP ($username, $password)"
.br
.ti -1c
.RI "\fBget\fP ($url, $postFields=null)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$token\fP"
.br
.ti -1c
.RI "\fB$ticket\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "authenticate ( $username,  $password)\fC [protected]\fP"

.SS "get ( $url,  $postFields = \fCnull\fP)\fC [protected]\fP"

.SS "passAuthentication (\fBProxmoxClass\fP $api)"

.SS "receiveAuthentication ( $token,  $ticket)"

.SH "Field Documentation"
.PP 
.SS "$ticket\fC [protected]\fP"

.SS "$token\fC [protected]\fP"

.SS "const API = 'https://192\&.168\&.80\&.21:8006/api2/json/'"


.SH "Author"
.PP 
Generated automatically by Doxygen for SINControl from the source code\&.
