.TH "SinException" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SinException \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (Exception $ex)"
.br
.ti -1c
.RI "\fB__toString\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fB$message\fP"
.br
.ti -1c
.RI "\fB$file\fP"
.br
.ti -1c
.RI "\fB$line\fP"
.br
.ti -1c
.RI "\fB$trace\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (Exception $ex)"

.SH "Member Function Documentation"
.PP 
.SS "__toString ()"

.SH "Field Documentation"
.PP 
.SS "$file\fC [private]\fP"

.SS "$line\fC [private]\fP"

.SS "$message\fC [private]\fP"

.SS "$trace\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for SINControl from the source code\&.
