.TH "StaffSystemTaskController" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StaffSystemTaskController \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBaseController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBindex\fP ()"
.br
.ti -1c
.RI "\fBcreate\fP ()"
.br
.ti -1c
.RI "\fBstore\fP ()"
.br
.ti -1c
.RI "\fBremove\fP ($task)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "create ()"

.SS "index ()"

.SS "remove ( $task)"

.SS "store ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for SINControl from the source code\&.
