.TH "StaffVirtualisationController" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StaffVirtualisationController \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBaseController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBindex\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "index ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for SINControl from the source code\&.
