.TH "/home/robin/NetbeansProjects/sincontrol/app/views/status.blade.php" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/robin/NetbeansProjects/sincontrol/app/views/status.blade.php \- 
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for SINControl from the source code\&.
