.TH "SystemTask" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemTask \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Eloquent\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($id, $type, $data, $start, $end, $interval, $exitcode, $started)"
.br
.ti -1c
.RI "\fB__get\fP ($property)"
.br
.ti -1c
.RI "\fB__set\fP ($property, $value)"
.br
.ti -1c
.RI "\fBsave\fP ($db)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBget\fP ($db)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$timestamps\fP = false"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$table\fP = 'system_task'"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fB$properties\fP = array ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $id,  $type,  $data,  $start,  $end,  $interval,  $exitcode,  $started)"

.SH "Member Function Documentation"
.PP 
.SS "__get ( $property)"

.SS "__set ( $property,  $value)"

.SS "static get ( $db)\fC [static]\fP"

.SS "save ( $db)"

.SH "Field Documentation"
.PP 
.SS "$properties = array ()\fC [private]\fP"

.SS "$table = 'system_task'\fC [protected]\fP"

.SS "$timestamps = false"


.SH "Author"
.PP 
Generated automatically by Doxygen for SINControl from the source code\&.
