.TH "SystemService" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemService \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBServiceApache\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatus\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBINIT\fP = 'sysvinit'"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBcmd\fP ($command, $returnAsString=false)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$name\fP"
.br
.ti -1c
.RI "\fB$serverName\fP"
.br
.ti -1c
.RI "\fB$software\fP"
.br
.ti -1c
.RI "\fB$ssh\fP"
.br
.ti -1c
.RI "\fB$needsSudo\fP = false"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "cmd ( $command,  $returnAsString = \fCfalse\fP)\fC [protected]\fP"

.SS "status ()"

.SH "Field Documentation"
.PP 
.SS "$name\fC [protected]\fP"

.SS "$needsSudo = false\fC [protected]\fP"

.SS "$serverName\fC [protected]\fP"

.SS "$software\fC [protected]\fP"

.SS "$ssh\fC [protected]\fP"

.SS "const INIT = 'sysvinit'"


.SH "Author"
.PP 
Generated automatically by Doxygen for SINControl from the source code\&.
