.TH "UserOwnedModel" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UserOwnedModel \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Eloquent\&.
.PP
Inherited by \fBLimitedUserOwnedModel\fP, and \fBUserLimit\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetUser\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "getUser ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for SINControl from the source code\&.
