.TH "UserLimit" 3 "Thu May 21 2015" "SINControl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UserLimit \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUserOwnedModel\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBgetLimit\fP (\fBUser\fP $user, $property)"
.br
.ti -1c
.RI "static \fBgetGlobalLimit\fP ($property)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$timestamps\fP = false"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$table\fP = 'user_limit'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "static getGlobalLimit ( $property)\fC [static]\fP"

.SS "static getLimit (\fBUser\fP $user,  $property)\fC [static]\fP"

.SH "Field Documentation"
.PP 
.SS "$table = 'user_limit'\fC [protected]\fP"

.SS "$timestamps = false"


.SH "Author"
.PP 
Generated automatically by Doxygen for SINControl from the source code\&.
